### ISSUE TITLE
Add spanish flag to SpellChecker

### ISSUE THREAD

**Issue by wh11204** [specialmart/cb-icons#4]
The spanish flag is missing from SpellChecker. I made PNG in all supported resolutions and later added a public domain SVG (my PNG are not generated from the SVG, but handcrafted).

The patch includes all of them, take what you need.

[0001-Add-spanish-flag-to-SpellChecker.zip](https://github.com/specialmart/cb-icons/files/3738901/0001-Add-spanish-flag-to-SpellChecker.zip)

**Comment by darmar-lt** [comment]
The patch was applied. Thank you.
